language: bash
matrix:
  include:
  - os: osx
    language: c
    addons:
      apt:
        packages:
        - libgnome-keyring-dev
        - icnsutils
        
    install:
    - nvm install 8
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - source ~/.bashrc
    - yarn
  - os: linux
    # before_install: eval "${CC=clang CXX=clang++ npm_config_clang=1}"
    compiler: clang
    addons:
      apt:
        packages:
        - libgnome-keyring-dev
        - icnsutils
    install:
    - nvm install 8
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - source ~/.bashrc
    - yarn
  - os: windows
    before_install:
    - export NVS_HOME="$HOME/.nvs"
    - git clone --single-branch https://github.com/jasongin/nvs $NVS_HOME
    - source $NVS_HOME/nvs.sh
    - export PATH=./node_modules/.bin:$PATH
    - nvs add lts
    - nvs use lts
    install:
    - npm -v
    - node -v
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - source ~/.bashrc
    - yarn
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
script:
- yarn run build
branches:
  only:
  - master
env:
  matrix:
    secure: oK0CUfGFU47F/0aPumYjmsgth6TB51sNhOjsNbTgX56QFQL/NMs4hGVwBm1F71D3Vkt5rKyc1Z71mKSMUteMnbJ6TM6h3l2Yf2vLvHXdCniUS03GqMPwK5a16EdqVtRix4f38s0J8ZOnHrE7CxuHIVm/ERkxjs348za0cw7Yj3I6pwSx3jXpGUbd9g0PiijcKl2xw44Vst9lKRrdmONpOcixUbYFMjWxZ4SYIDv5o+MFx3mZCRRH/5hnZvevHEOKPvXgT2j0yIq6fg7jEvTgJZQbYztT+UjLxAnzIILabBNfkXXMbBQnkAWsyfZW85Y/M7qOBHbKUa4Lh3bil8OvbGeaSMuMGuc1UWlKpzE1ahB4ZtAVhWsKOfaG5hyn2/3vxTBQt7HzY1n9AvbtzfCmzvkm3H+y6HX1RY5PXcSQ+QolIYGS6LVZhbNe1QkY1rZVHKzPhNZjz9y67aIgJ5gKpofE9R9aJ5fJFbxPrrZKqrNYN18RKOCNLc5+N4lLccTWTLHANYLcKyYQpzTYxhcOSfb7eqxCjQ+V11EiHhFIzjQ3T6wtwI5YMYlxLqg2UkesMdl+5utOBAGC2rcIx2fSA+Mjtt1otxcQpmGgtqAYQDoS942GOL2TuJpLz1xROguNnFqou+UG0C2xGctogFztEmAdpdoVF+Oq5WBRDbxXpAM=
